import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "./component/sidebar";
import Providers from '@/app/component/provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className='grid
        grid-cols-6
        grid-rows-1
        min-h-screen 
        bg-grey-100'>
          <div className='col-span-2 xl:col-span-1 overflow-visible'>
            <Sidebar />
          </div>
          <main className="col-span-4 xl:col-span-5 
          overflow-x-hidden overflow-y-auto
        bg-gray-200">
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
